version = 1

[[annotations]]
path = [
    "REUSE.toml",
    "nuget.config",
    "global.json",
    "**/packages.lock.json",
    "scripts/ps5_names.txt",
    "src/SharpEmu.GUI/Languages/**",
    "src/SharpEmu.ShaderCompiler.Metal/Templates/**",
    "tests/SharpEmu.ShaderCompiler.Metal.Tests/Goldens/**",
    "_logs/**",
    ".github/images/**",
    ".github/pull_request_template.md",
    "assets/images/**",
    "emma-story/assets/art/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "SharpEmu Emulator Project"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "src/SharpEmu.GUI/Assets/Fonts/MaterialSymbolsRounded-*.ttf"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Google LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "src/SharpEmu.LibAtrac9/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Alex Barney"
SPDX-License-Identifier = "MIT"
